// Code generated by "stringer -type=CRC16Model"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CRC_16_ARC-0]
	_ = x[CRC_16_CDMA2000-1]
	_ = x[CRC_16_CMS-2]
	_ = x[CRC_16_DDS_110-3]
	_ = x[CRC_16_DECT_R-4]
	_ = x[CRC_16_DECT_X-5]
	_ = x[CRC_16_DNP-6]
	_ = x[CRC_16_EN_13757-7]
	_ = x[CRC_16_GENIBUS-8]
	_ = x[CRC_16_GSM-9]
	_ = x[CRC_16_IBM_3740-10]
	_ = x[CRC_16_IBM_SDLC-11]
	_ = x[CRC_16_ISO_IEC_14443_3_A-12]
	_ = x[CRC_16_KERMIT-13]
	_ = x[CRC_16_LJ1200-14]
	_ = x[CRC_16_M17-15]
	_ = x[CRC_16_MAXIM_DOW-16]
	_ = x[CRC_16_MCRF4XX-17]
	_ = x[CRC_16_MODBUS-18]
	_ = x[CRC_16_NRSC_5-19]
	_ = x[CRC_16_OPENSAFETY_A-20]
	_ = x[CRC_16_OPENSAFETY_B-21]
	_ = x[CRC_16_PROFIBUS-22]
	_ = x[CRC_16_RIELLO-23]
	_ = x[CRC_16_SPI_FUJITSU-24]
	_ = x[CRC_16_T10_DIF-25]
	_ = x[CRC_16_TELEDISK-26]
	_ = x[CRC_16_TMS37157-27]
	_ = x[CRC_16_UMTS-28]
	_ = x[CRC_16_USB-29]
	_ = x[CRC_16_XMODEM-30]
}

const _CRC16Model_name = "CRC_16_ARCCRC_16_CDMA2000CRC_16_CMSCRC_16_DDS_110CRC_16_DECT_RCRC_16_DECT_XCRC_16_DNPCRC_16_EN_13757CRC_16_GENIBUSCRC_16_GSMCRC_16_IBM_3740CRC_16_IBM_SDLCCRC_16_ISO_IEC_14443_3_ACRC_16_KERMITCRC_16_LJ1200CRC_16_M17CRC_16_MAXIM_DOWCRC_16_MCRF4XXCRC_16_MODBUSCRC_16_NRSC_5CRC_16_OPENSAFETY_ACRC_16_OPENSAFETY_BCRC_16_PROFIBUSCRC_16_RIELLOCRC_16_SPI_FUJITSUCRC_16_T10_DIFCRC_16_TELEDISKCRC_16_TMS37157CRC_16_UMTSCRC_16_USBCRC_16_XMODEM"

var _CRC16Model_index = [...]uint16{0, 10, 25, 35, 49, 62, 75, 85, 100, 114, 124, 139, 154, 178, 191, 204, 214, 230, 244, 257, 270, 289, 308, 323, 336, 354, 368, 383, 398, 409, 419, 432}

func (i CRC16Model) String() string {
	if i < 0 || i >= CRC16Model(len(_CRC16Model_index)-1) {
		return "CRC16Model(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CRC16Model_name[_CRC16Model_index[i]:_CRC16Model_index[i+1]]
}
